### ISSUE TITLE
编译不过了

### ISSUE THREAD

**Issue by P-PPPP** [A-Soul-Database/Web-Interface#3]
```
Bundle with webpack 5...

● Webpack █████████████████████████ building (10%) 0/1 entries 0/0 dependencies 0
/0 modules 0 active 
 

(node:26485) [DEP_WEBPACK_CONFIGURATION_OPTIMIZATION_NO_EMIT_ON_ERRORS] DeprecationWarning: optimization.noEmitOnErrors is deprecated in favor of optimization.emitOnErrors
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:26485) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:26485) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/root/Web-Interface/build/make-front-end/node_modules/_@umijs_deps@3.5.31@@umijs/deps/compiled/webpack/5/bundle5.js:184154:18)
    at BulkUpdateDecorator.update (/root/Web-Interface/build/make-front-end/node_modules/_@umijs_deps@3.5.31@@umijs/deps/compiled/webpack/5/bundle5.js:184055:50)
    at /root/Web-Interface/build/make-front-end/node_modules/_@umijs_deps@3.5.31@@umijs/deps/compiled/webpack/5/bundle5.js:107101:9
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at processImmediate (node:internal/timers:442:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
```

**Comment by P-PPPP** [comment]
solved

**Comment by P-PPPP** [comment]
export NODE_OPTIONS=--openssl-legacy-provider;
